name: Playwright Tests
on:
  push:
    branches: [ trunk ]
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  downstream:
    runs-on: ubuntu-latest
    if: github.repository == 'shopware/shopware'
    steps:
      - uses: shopware/github-actions/.github/actions/downstream@add-composite-actions
        with:
          repo: shopware/actions-test
          workflow: test
          ref: trunk
          timeout: 45s
